Models/Employee.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeLeaves.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Lastname { get; set; }
        public string Firstname { get; set; } = String.Empty;

        [NotMapped]
        [DisplayName("Name")]
        public string FullName => $"{Lastname} {Firstname}";
        public string Email { get; set; } = String.Empty;
        [DisplayName("Date of birth"), DataType(DataType.Date)]
        public DateTime? DateOfBirth { get; set; }
        [DisplayName("Date of hire"), DataType(DataType.Date)]
        public DateTime? DateOfHire { get; set; }
        [DisplayName("Date of redundancy"), DataType(DataType.Date)]
        public DateTime? DateOfRedundancy { get; set; }
        [Required]
        [DisplayName("Department")]
        public int DepartmentId { get; set; }
        [DisplayName("Approver")]
        [Required]
        public int ApproverId { get; set; }
        [DisplayName("Is Approver")]
        public bool IsApprover { get; set; } = false;
        [DisplayName("Is Manager")]
        public bool IsManager { get; set; } = false;
        [DisplayName("Is Administrator")]
        public bool IsAdmin { get; set; } = false;
        public virtual Department? Department { get; set; }
        public virtual Employee? Approver { get; set; }
        public List<LeaveRequest> LeaveRequests { get; set; } = new List<LeaveRequest>();
    }
}

Controllers/EmployeeStatisticsController.cs
using EmployeeLeaves.Data;
using EmployeeLeaves.Enums;
using EmployeeLeaves.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace EmployeeLeaves.Controllers
{
    public class EmployeeStatisticsController : Controller
    {
        private readonly LeavesContext _context;

        public EmployeeStatisticsController(LeavesContext context)
        {
            _context = context;
        }
        public IActionResult Index(int EmployeeID, int? Year)
        {
            int _year = Year ?? DateTime.Now.Year;
            var employee = _context.Employees.Include(e => e.LeaveRequests).ThenInclude(r => r.RequestedDays.Where(k => k.Year == _year)).FirstOrDefault<Employee>(e => e.Id == EmployeeID);
            
            if (employee == null)
                return NotFound();

            EmployeeStatisticsViewModel employeeStatistics = new EmployeeStatisticsViewModel();

            employeeStatistics.Employee = employee;
            employeeStatistics.Year = _year;
            employeeStatistics.LeaveRequests = employee.LeaveRequests.ToList();
            employeeStatistics.AnnualLeaveDays = 25;
            employeeStatistics.LeaveDaysApprovedList = employee.LeaveRequests.Where(x => x.Status == RequestStatus.Approved).SelectMany(x => x.RequestedDays.Select(i => i.LeaveDay)).ToList();
            //employeeStatistics.LeaveDaysApproved = employeeStatistics.LeaveDaysApprovedList.Count(); // employee.LeaveRequests.Where(x => x.Status == RequestStatus.Approved).SelectMany(x => x.RequestedDays).Count();            
            employeeStatistics.LeaveDaysPendingApproval = employee.LeaveRequests.Where(x => x.Status == RequestStatus.Pending).SelectMany(x => x.RequestedDays).Count();
            employeeStatistics.LeaveDaysRejected = employee.LeaveRequests.Where(x => x.Status == RequestStatus.Rejected).SelectMany(x => x.RequestedDays).Count(); ;
            employeeStatistics.LeaveDaysRemaining = employeeStatistics.AnnualLeaveDays - employeeStatistics.LeaveDaysApprovedList.Count() - employeeStatistics.LeaveDaysPendingApproval;

            var leaveDaysDictionary = employee.LeaveRequests
                .Where(x => x.Status == RequestStatus.Approved)
                .SelectMany(x => x.RequestedDays)
                .Select(i => i.LeaveDay).Where(i => i.Year == _year)
                .GroupBy(i => i.Month)
                .Select(i => new { minas = new DateTime(_year, i.Key, 1).ToString("MMM", CultureInfo.InvariantCulture).ToUpper(), count = i.Count() })
                .ToDictionary(i => i.minas, i => i.count);

            var dict = new Dictionary<string, int>();

            for (int i = 1; i <= 12; i++)
            {
                DateOnly d = new DateOnly(_year, i, 1);
                string key = d.ToString("MMM", CultureInfo.InvariantCulture).ToUpper();
                dict.Add(key, GetValueFromDictionary(leaveDaysDictionary, key));
            }

            employeeStatistics.LeaveDaysPerMonth = dict;

            return View(employeeStatistics);
        }

        private int GetValueFromDictionary(Dictionary<string, int> dic, string key)
        {
            foreach(KeyValuePair<string, int> entry in dic)
            {
                if (entry.Key == key)
                    return entry.Value;
            }
            return 0;
        }

    }
}

Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeeLeaves.Data;
using EmployeeLeaves.Models;

namespace EmployeeLeaves.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly LeavesContext _context;

        public EmployeesController(LeavesContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index(int? page, int? pageSize)
        {
            var leavesContext = _context.Employees.Include(e => e.Department);

            //int _pageSize = (int)(pageSize != null ? pageSize : 10);
            int _pageSize = (int)(pageSize != null ? pageSize : leavesContext.Count());
            int _page = (int)(page != null ? page : 1);
            _page = _page > 0 ? _page : 1;

            ViewBag.PageNo = _page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((decimal)leavesContext.Count() / _pageSize);

            //ViewData["PageNo"] = _page;
            //ViewData["PageSize"] = pageSize;
            //ViewData["TotalPages"] = (int)Math.Ceiling((decimal)leavesContext.Count() / _pageSize);

            return View(await leavesContext.Skip((_page - 1) * _pageSize).Take(_pageSize).ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .Include(e => e.Approver)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            ViewData["DepartmentsList"] = new SelectList(_context.Departments.OrderBy(d => d.Title), "Id", "Title");
            ViewData["ApproversList"] = new SelectList(_context.Employees.Where(e => e.IsApprover == true).OrderBy(e => e.Lastname).ThenBy(e => e.Firstname), "Id", "FullName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Lastname,Firstname,Email,DateOfBirth,DateOfHire,DateOfRedundancy,DepartmentId,ApproverId,IsApprover,IsManager,IsAdmin")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentsList"] = new SelectList(_context.Departments.OrderBy(d => d.Title), "Id", "Title", employee.DepartmentId);
            ViewData["ApproversList"] = new SelectList(_context.Employees.Where(e => e.IsApprover == true).OrderBy(e => e.Lastname).ThenBy(e => e.Firstname), "Id", "FullName", employee.ApproverId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .Include(e => e.Approver)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (employee == null)
            {
                return NotFound();
            }
            ViewData["DepartmentsList"] = new SelectList(_context.Departments.OrderBy(d => d.Title), "Id", "Title", employee.DepartmentId);
            ViewData["ApproversList"] = new SelectList(_context.Employees.Where(e => e.IsApprover == true).OrderBy(e => e.Lastname).ThenBy(e => e.Firstname), "Id", "FullName", employee.ApproverId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Lastname,Firstname,Email,DateOfBirth,DateOfHire,DateOfRedundancy,DepartmentId,ApproverId,IsApprover,IsManager,IsAdmin")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentsList"] = new SelectList(_context.Departments.OrderBy(d => d.Title), "Id", "Title", employee.DepartmentId);
            ViewData["ApproversList"] = new SelectList(_context.Employees.Where(e => e.IsApprover == true).OrderBy(e => e.Lastname).ThenBy(e => e.Firstname), "Id", "FullName", employee.ApproverId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Department)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

Views/Employees/Create.cshtml
@model EmployeeLeaves.Models.Employee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="dst-page-title">
    <h1><i class='fas fa-user-plus'></i>&nbsp;&nbsp;&nbsp;Add new employee</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfHire" class="control-label"></label>
                <input asp-for="DateOfHire" class="form-control" />
                <span asp-validation-for="DateOfHire" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfRedundancy" class="control-label"></label>
                <input asp-for="DateOfRedundancy" class="form-control" />
                <span asp-validation-for="DateOfRedundancy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentsList"><option>Select Department</option></select>
            </div>
            <div class="form-group">
                <label asp-for="ApproverId" class="control-label"></label>
                <select asp-for="ApproverId" class="form-control" asp-items="ViewBag.ApproversList"></select>
                @* <input asp-for="ApproverId" class="form-control" /> *@
                <span asp-validation-for="ApproverId" class="text-danger"></span>
            </div>
            <div class="form-group form-check form-switch">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsApprover" /> @Html.DisplayNameFor(model => model.IsApprover)
                </label>
            </div>
            <div class="form-group form-check form-switch">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsManager" /> @Html.DisplayNameFor(model => model.IsManager)
                </label>
            </div>
            <div class="form-group form-check form-switch">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAdmin" /> @Html.DisplayNameFor(model => model.IsAdmin)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Employees/Delete.cshtml
@model EmployeeLeaves.Models.Employee

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="dst-page-title">
    <h1><i class='fas fa-user-times'></i>&nbsp;&nbsp;&nbsp;Delete employee</h1>
</div>

<h3>Are you sure you want to delete this employee?</h3>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfHire)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfHire)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfRedundancy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfRedundancy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApproverId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApproverId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsApprover)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsApprover)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsManager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsManager)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Employees/Details.cshtml
@model EmployeeLeaves.Models.Employee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="dst-page-title">
    <h1><i class='fas fa-user-check'></i>&nbsp;&nbsp;&nbsp;Employee details</h1>
</div>

<div>   
    <dl class="row">
        <div class="dst-details-box">
            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Lastname)
            </dt>
            <dd class = "col-sm-4">
                @Html.DisplayFor(model => model.Lastname)
            </dd>

            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Firstname)
            </dt>
            <dd class = "col-sm-4">
                @Html.DisplayFor(model => model.Firstname)
            </dd>
        </div>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd class="col-sm-4">
            @Html.DisplayFor(model => model.Department.Title)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfHire)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.DateOfHire)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfRedundancy)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.DateOfRedundancy)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApproverId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Approver.FullName)
        </dd>

        @* <div class="dst-details-box"> *@

            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsApprover)
            </dt>
            <dd class = "col-sm-2">
                @Html.DisplayFor(model => model.IsApprover)
            </dd>

            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsManager)
            </dt>
            <dd class = "col-sm-2">
                @Html.DisplayFor(model => model.IsManager)
            </dd>

            <dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.IsAdmin)
            </dt>
            <dd class = "col-sm-2">
                @Html.DisplayFor(model => model.IsAdmin)
            </dd>

        @* </div> *@
        

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

@* @section Scripts {
    <script>
        $(function() {
            alert("Test");
        });
    </script>
} *@

Views/Employees/Index.cshtml
@model IEnumerable<EmployeeLeaves.Models.Employee>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="dst-page-title">
    <h1><i class='fas fa-user-alt'></i>&nbsp;&nbsp;&nbsp;Employees List</h1>
</div>

<div class="row opensans_font" style="margin-bottom:10px;">
    <div class="col-sm-4" style="text-align:left;">
        <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create", "Employees")'"><i class='fas fa-plus' style="margin-right:8px;"></i>Add Employee</button>
    </div>
    <div class="col-sm-4" style="text-align:left;">
        @* <div class="form-group">
            <label for="sel1">Select page size:</label>
            <select class="form-control" id="pageSize">
                <option>5</option>
                <option>10</option>
                <option>20</option>
                <option>50</option>
            </select>
        </div> *@
        @* <div class="list-group list-group-horizontal">
            <a href="#" class="list-group-item active">10</a>
            <a href="#" class="list-group-item">20</a>
            <a href="#" class="list-group-item">30</a>
            <a href="#" class="list-group-item">50</a>
        </div> *@
    </div>
    @* <div class="col-sm-4" style="text-align:center; padding-top: 7px;">
        <i id="ToggleShowInactive" class="fa fa-toggle-off" style="font-size:x-large; margin-right:10px; color:lightgrey; cursor:pointer;"></i><span>Αποχωρήσαντες</span>
    </div> *@
    <div class="col-sm-4">
        @* <div class="input-group" style="text-align:right;">
            <input class="form-control" id="searchInput" type="text" placeholder="Search..">
            <span class="input-group-addon" style="background-color:inherit; cursor:pointer; font-size:large;" id="btnClearFilter"><i class="fa fa-close"></i></span>
        </div>  *@     
    </div>
</div>

<table class="table">
    <thead class="dst-table-header">
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>           
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfHire)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfRedundancy)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.ApproverId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsApprover)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsManager)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAdmin)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@{
    int RowNo = 0;
}
@foreach (var item in Model) {
    <tr class="dst-table-row">
        <td>
            @{
                RowNo++;
            } @(RowNo.ToString() + ".")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.Title)
        </td>
            @* <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>           
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth, "{0:MM/dd/yyyy}")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfHire, "{0:MM/dd/yyyy}")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfRedundancy, "{0:MM/dd/yyyy}")
        </td> *@
        <td>
            @Html.DisplayFor(modelItem => item.Approver.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsApprover)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsManager)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAdmin)
        </td>
            
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id" title="Edit"><span class="far fa-edit" style="font-size:large;"></span></a>&nbsp;&nbsp;
            <a asp-action="Details" asp-route-id="@item.Id" title="Details"><span class="far fa-file-alt" style="font-size:large;"></span></a>&nbsp;&nbsp;
            <a asp-controller="EmployeeStatistics" asp-action="Index" asp-route-employeeid="@item.Id" title="Statistics"><span class="fas fa-chart-pie" style="font-size:large;"></span></a>&nbsp;&nbsp;
            <a asp-action="Delete" asp-route-id="@item.Id" title="Delete"><span class="far fa-trash-alt" style="font-size:large; color:red;"></span></a>
        </td>
    </tr>
}

    </tbody>
</table>
<div class="row">
    <div class="col-sm-3">
        <div class="list-group list-group-horizontal list-group-horizontal-sm dst-page-size">
            <a asp-action="Index" asp-route-page="1" asp-route-pagesize="10" class="list-group-item @((int?)ViewBag.PageSize == 10 ? "active" : "")">10</a>
            <a asp-action="Index" asp-route-page="1" asp-route-pagesize="25" class="list-group-item @((int?)ViewBag.PageSize == 25 ? "active" : "")">25</a>
            <a asp-action="Index" asp-route-page="1" asp-route-pagesize="50" class="list-group-item @((int?)ViewBag.PageSize == 50 ? "active" : "")">50</a>
            <a asp-action="Index" asp-route-page="1" class="list-group-item @(ViewBag.PageSize == null ? "active" : "")">ALL</a>
        </div>
    </div>
    <div class="col-sm-6">
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item @((int)ViewBag.PageNo == 1 ? "disabled" : "")"><a class="page-link" asp-action="Index" asp-route-page="1"><i class="fas fa-angle-double-left" title="First"></i></a></li>
            <li class="page-item @((int)ViewBag.PageNo == 1 ? "disabled" : "")"><a class="page-link" asp-action="Index" asp-route-page=@((int)ViewBag.PageNo > 1 ? (int)ViewBag.PageNo - 1 : 1)><i class="fas fa-angle-left" title="Previous"></i></a></li>
            @for(int i = 1; i<=(int)ViewBag.TotalPages; i++) 
            {
                <li class="page-item"><a class="page-link @((int)ViewBag.PageNo == i ? "dst-bold" : "")" asp-action="Index" asp-route-page=@i>@i</a></li>
            }
        
            <li class="page-item @((int)ViewBag.PageNo == (int)ViewBag.TotalPages ? "disabled" : "")"><a class="page-link" asp-action="Index" asp-route-page=@((int)ViewBag.PageNo + 1)><i class="fas fa-angle-right" title="Next"></i></a></li>
            <li class="page-item @((int)ViewBag.PageNo == (int)ViewBag.TotalPages ? "disabled" : "")"><a class="page-link" asp-action="Index" asp-route-page=@((int)ViewBag.TotalPages)><i class="fas fa-angle-double-right" title="Last"></i></a></li>
        </ul>
    </div>
    <div class="col-sm-3 dst-page-counter">
        @("Page " + ViewBag.PageNo + " of " + ViewBag.TotalPages)
    </div>
</div>

<!-- The Modal -->
<div class="modal fade" id="myModal">
<div class="modal-dialog modal-sm">
    <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Modal Heading</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
            Modal body..
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>

    </div>
</div>
</div>